### ISSUE TITLE
disappointing results for A4 pages

### ISSUE THREAD

**Issue by drzraf** [ricardobnjunior/HU-PageScan#1]
Dear,
I tried the pretrained model on a set of scanned pages but being disappointed by results.

![Screenshot from 2023-11-12 12-59-27](https://github.com/ricardobnjunior/HU-PageScan/assets/1169926/539b7ead-4aab-4822-b4f0-7a54a29731cb)

I think these are canny-edges friendly and would have expected a far better rectangles detection.

![Screenshot from 2023-11-12 13-22-53](https://github.com/ricardobnjunior/HU-PageScan/assets/1169926/16ae204b-3f46-474c-b73a-06bc588e56c4)

- Indeed little space is left for background / margin (less than 10% ?), mostly because legible A4 pages need higher resolution (thus smaller camera-document distance and consequently less borders)
- Multiple documents have one folded corner (because of the staple) what may impact quadrilateral contour search
... but I doubt these explain the overall limited document detection.

**Comment by ricardobnjunior** [comment]
Dear colleague,

Thank you for experimenting with the HU-PageScan algorithm in your work. I am pleased to know that this model has sparked your interest. However, I understand that the results obtained on your dataset were not as satisfactory as expected. Let me share some thoughts on this.

The HU-PageScan was developed and optimized specifically for the dataset used in our research. Each dataset has its peculiarities, which include variations in format, style, image quality, and other factors. These differences can significantly impact the performance of a machine learning algorithm, especially in complex tasks like document page segmentation.

When it comes to applying a trained model to a new dataset, it is common that adjustments are needed to optimize its performance. This process is known as transfer learning. Transfer learning involves adapting an existing model to a new context, which may include fine-tuning some of the model's parameters or additional training with data from the new domain.

I recommend considering the application of transfer learning techniques to the HU-PageScan to adapt it to your dataset. This could involve re-adjusting the model's parameters using a representative subset of your data or implementing domain-specific data augmentation techniques.

**Comment by drzraf** [comment]
For anyone reaching this issue, I finally went with https://github.com/cvlab-stonybrook/PaperEdge which gave me **very good** results. The unwrapping product of their model is a bit aggressive (distortions) but cropping is excellent.
